# Generated by Django 3.2.25 on 2024-04-26 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ems_dev', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department', to='ems_dev.department')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='ems_dev.job')),
            ],
        ),
    ]
